kind: DaemonSet
apiVersion: apps/v1 

metadata:
  name: nginx-deamonset
  namespace: nginx

spec:
  selector:
    matchLabels:
      app: nginx


  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
        namespace: nginx

    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
